<a href="https://colab.research.google.com/github/Anushka23ja/MSIS502/blob/main/MSIS_502_Session1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.  Python as a calculator

In [ ]:
2+1

3

In [ ]:
2**3

8

In [ ]:
3/10

0.3

1.1 Assigning Values to Variables

In [ ]:
counter = 100 # An integer assignment
miles = 1000.0 # A floating point
name = "John" # A string

print(counter)
print(miles)
print(name)

100
1000.0
John


In [ ]:
a = 1
b = 2
print(a,b)

1 2


In [ ]:
# Arithmetic with variables
print(a + b)
print(a + 10)
print(a/b)

3
11
0.5


In [ ]:
# create variable c
c = a + b
print(c)

3


In [ ]:
my_variable = 10
print(my_variable)

10


2.2 Python Lists

In [ ]:
# A list is a compound data type, you can group values together
a = 10
my_list = [ a, 'abcd', 786 , 2.23, 'john']
print(my_list)

[10, 'abcd', 786, 2.23, 'john']


In [ ]:
tinylist = [123, 'john']
print(tinylist * 2) # Prints list two times
print(my_list + tinylist) # Prints concatenated lists

[123, 'john', 123, 'john']
[10, 'abcd', 786, 2.23, 'john', 123, 'john']


In [ ]:
print(my_list) # Prints complete list
print(my_list[0]) # Prints first element of the list
print(my_list[1:3]) # Prints elements starting from 2nd till 3rd
print(my_list[2:]) # Prints elements starting from 3rd element
print(my_list[2:-1]) #IF YOU WANT THE VERY LAST VALUE print(my_list[2])
print(my_list[2])
print(my_list[-1]) # Prints the last element
print(my_list[-3:-1])

[10, 'abcd', 786, 2.23, 'john']
10
['abcd', 786]
[786, 2.23, 'john']
[786, 2.23]
786
john
[786, 2.23]


In [ ]:
# Variables can also be used as indexing
myStart = 2
print(my_list[myStart])
# get the length of a list
len(my_list)

786


5

Practice Problem

In [ ]:
ad_spend = ["Monday", 120.0, "Tuesday", 150.5, "Wednesday", 135.0, "Thursday", 160.0, "Friday", 175.5, "Saturday", 190.0, "Sunday", 145.0]
weekday_spend = ad_spend[:10]
weekend_spend = ad_spend[10:]
print(weekday_spend)
print(weekend_spend)

['Monday', 120.0, 'Tuesday', 150.5, 'Wednesday', 135.0, 'Thursday', 160.0, 'Friday', 175.5]
['Saturday', 190.0, 'Sunday', 145.0]


2.2.3 List Manipulation

In [ ]:
x = ['a', 'b', 'c', 'd']
x[1] = 'r'
x[2:] = ['s', 't']
print(x)

['a', 'r', 's', 't']


In [ ]:
x = ['a', 'b', 'c', 'd']
y = x + ['e', 'f']
print(y)

['a', 'b', 'c', 'd', 'e', 'f']


3. Packages

In [ ]:
import math

In [ ]:
math.pi #math/A/B/C/pi --> math.A.B.C.pi

3.141592653589793

In [ ]:
r = 0.3
area = math.pi * r * r
print(area)

0.2827433388230814


In [ ]:
from math import pi
r = 0.3
area = pi * r * r
print(area)

0.2827433388230814


Practice Problem

In [ ]:
from math import sqrt
num = 10
tot = sqrt(num)
print(tot)

3.1622776601683795


4. NumPy

In [ ]:
import numpy as np

# the list length represents the length of some rectangles
# the list width represents the width of some rectangles
length = [2, 4, 6, 8]
width = [1.4, 3.2, 1, 6]

# we want to calculate area of the rectangles
# Convert lists to NumPy arrays for element-wise multiplication
length_np = np.array(length)
width_np = np.array(width)

area = length_np * width_np
print("Area of rectangles:", area)

# or double the length of every rectangle
doubled_length = length_np * 2
print("Doubled length:", doubled_length)

Area of rectangles: [ 2.8 12.8  6.  48. ]
Doubled length: [ 4  8 12 16]


In [ ]:
import numpy as np # you can now refer to numpy as np
# use np.array() to create a numpy array from length.
np_length = np.array(length) # np.array is a function to do the type conversion
print(np_length)

[2 4 6 8]


In [ ]:
print(np_length + 1)

[3 5 7 9]


In [ ]:
print (np_length * 2)

[ 4  8 12 16]


In [ ]:
print(np_length)
print(width_np)

[2 4 6 8]
[1.4 3.2 1.  6. ]


In [ ]:
np_width = np.array(width)
area = np_length * np_width
print(area)
print(np_width)

[ 2.8 12.8  6.  48. ]
[1.4 3.2 1.  6. ]


Practice Problem

In [ ]:
ad_spend = [1200, 950, 1600, 870, 1320]
revenue_local = [3000, 2200, 4100, 1900, 3400]
exchange_rates = [1.0, 0.85, 1.1, 0.9, 1.2]

In [ ]:
spend_usd = np.array(ad_spend)
revenue_usd = np.array(revenue_local)
roi = (revenue_usd - spend_usd) / spend_usd
print(roi)

[1.5        1.31578947 1.5625     1.18390805 1.57575758]


4.2 Numpy array indexing and slicing

In [ ]:
x = [4 , 9 , 6, 3, 1]
print(x[1])
y = np.array(x)
print(y[1])
print(y[1:3])
print(y[3:])
print(y[-2])

9
9
[9 6]
[3 1]
3


In [ ]:
x = [4,9,6,3,1]
y = np.array(x)
print(y)

[4 9 6 3 1]


In [ ]:
my_index = np.array ([True,True,False,False, False])
print(my_index)

[ True  True False False False]


In [ ]:
y[my_index]

array([4, 9])

In [ ]:
y

array([4, 9, 6, 3, 1])

In [ ]:
high = y > 5
print(high)

[False  True  True False False]


In [ ]:
y[high]

array([9, 6])

In [ ]:
y[1]

np.int64(9)

In [ ]:
y[[0,4,2]]

array([4, 1, 6])

In [ ]:
y[[0,4,2,0,0,0,0]]

array([4, 1, 6, 4, 4, 4, 4])

In [ ]:
product_A = [250,300,280,321]
product_B = [180,200,190,210]

list_2d = [product_A, product_B]
print(list_2d)

[[250, 300, 280, 321], [180, 200, 190, 210]]


In [ ]:
np_2d = np.array(list_2d)
print(np_2d)

[[250 300 280 321]
 [180 200 190 210]]


In [ ]:
np_2d.shape

(2, 4)

4.5.1 Indexing and Slicing

In [ ]:
# Select the height and weight of the third and fourth player
np_2d[:,1:3] # : stands for all the rows
# product A of the second and third region
np_2d[0,1:3]

array([300, 280])

In [ ]:
# If you only want to retrieve the sales for product A
np_2d[0,:] # it is equivalent to np_2d[0] which omits the column index
np_2d[0, [0,2,3] ]

array([250, 280, 321])

4.5.2 Aggregation

In [ ]:
print(np_2d[0,1:3])

[300 280]


In [ ]:
data = np.array([[1,2],[5,2],[4,6]])
print(data)

[[1 2]
 [5 2]
 [4 6]]
